2025-09-07 08:51:17.105923: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1757235077.122355 3514431 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1757235077.127409 3514431 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1757235077.141040 3514431 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1757235077.141072 3514431 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1757235077.141074 3514431 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1757235077.141077 3514431 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-09-07 08:51:17.145637: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:From /home/giung/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/compat/v2_compat.py:98: disable_resource_variables (from tensorflow.python.ops.resource_variables_toggle) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "/home/giung/MAGI-TS-3/scripts/claude_magix_exp_inferred.py", line 346, in <module>
    main()
  File "/home/giung/MAGI-TS-3/scripts/claude_magix_exp_inferred.py", line 68, in main
    data = np.loadtxt('data/321/%s.txt' %(example))
  File "/home/giung/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/lib/_npyio_impl.py", line 1381, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/giung/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/lib/_npyio_impl.py", line 997, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/giung/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 192, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/giung/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 532, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: data/321/fn.txt not found.
